import React from "react";
import BusSeatSelection from "../../src/components/buses/BusSeatSelection";
import PassengerDetailsForm from "../../src/components/buses/PassangersDetailsForm";
import BusSearch from "../../src/components/buses/BusSearch";
import PopularRoutes from "../../src/components/buses/PopularRoutes";

// ─── Seat layout helper ───────────────────────
// s(id, status, price) => seat object
// null => aisle gap
const s = (id, status, price) => ({ id, status, price });

const Index = () => {
  const sampleBuses = [
    {
      id: 1,
      operatorName: "Neeta tours & travels",
      busType: "Bharat Benz A/C Seater (2+2)",
      departureTime: "08:40",
      departureDate: "02 Jan",
      from: "Mumbai",
      arrivalTime: "13:50",
      arrivalDate: "02 Jan",
      to: "Pune",
      duration: "6h 10m",
      price: 1650,
      seatsAvailable: 15,
      priceTiers: [374, 450, 495, 540],
      footerTags: [
        "Boarding & Dropping points",
        "Cancellations Policy",
        "Amenities",
      ],
      boardingPoints: [
        {
          name: "Andheri (E) - Shivaji Travels",
          subLabel: "Andheri East",
          time: "22:50",
        },
        { name: "Dadar - Kailash Travels", subLabel: "Dadar", time: "25:00" },
        { name: "Bandra - Express Stop", subLabel: "Bandra", time: "23:30" },
        { name: "Borivali Depot", subLabel: "Borivali", time: "21:45" },
        { name: "Thane Station", subLabel: "Thane", time: "20:30" },
      ],
      seatLayout: [
        [
          s("A1", "available", 374),
          null,
          s("A2", "booked", 374),
          s("A3", "available", 374),
          null,
          s("B1", "booked", 450),
          s("B2", "available", 450),
          s("B3", "available", 450),
          s("B4", "available", 450),
        ],
        [
          s("A4", "booked", 374),
          null,
          s("A5", "booked", 374),
          s("A6", "available", 374),
          null,
          s("B5", "available", 450),
          s("B6", "available", 450),
          s("F1", "female", 495),
          s("F2", "female", 495),
        ],
        [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          s("A9", "available", 374),
        ],
        [
          s("F3", "female", 495),
          s("F4", "female", 495),
          s("F5", "female", 495),
          s("F6", "female", 495),
          null,
          s("M1", "male", 540),
          s("M2", "male", 540),
          s("M3", "male", 540),
          s("M4", "male", 540),
        ],
        [
          s("A10", "available", 374),
          s("A11", "available", 374),
          s("A12", "available", 374),
          s("A13", "available", 374),
          null,
          s("M5", "male", 540),
          s("M6", "male", 540),
          s("M7", "male", 540),
          s("M8", "male", 540),
        ],
      ],
    },
    {
      id: 2,
      operatorName: "Neeta tours & travels",
      busType: "Bharat Benz A/C Seater (2+2)",
      departureTime: "08:40",
      departureDate: "02 Jan",
      from: "Mumbai",
      arrivalTime: "13:50",
      arrivalDate: "02 Jan",
      to: "Pune",
      duration: "6h 10m",
      price: 1650,
      seatsAvailable: 12,
      priceTiers: [374, 450, 495, 540],
      footerTags: [
        "Boarding & Dropping points",
        "Cancellations Policy",
        "Amenities",
      ],
      boardingPoints: [
        {
          name: "Andheri (E) - Shivaji Travels",
          subLabel: "Andheri East",
          time: "22:50",
        },
        { name: "Dadar - Kailash Travels", subLabel: "Dadar", time: "25:00" },
        { name: "Bandra - Express Stop", subLabel: "Bandra", time: "23:30" },
        { name: "Borivali Depot", subLabel: "Borivali", time: "21:45" },
      ],
      seatLayout: [
        [
          s("A1", "booked", 374),
          null,
          s("A2", "available", 374),
          s("A3", "booked", 374),
          null,
          s("B1", "available", 450),
          s("B2", "available", 450),
          s("B3", "booked", 450),
          s("B4", "available", 450),
        ],
        [
          s("A4", "available", 374),
          null,
          s("A5", "available", 374),
          s("A6", "booked", 374),
          null,
          s("B5", "booked", 450),
          s("B6", "available", 450),
          s("F1", "female", 495),
          s("F2", "female", 495),
        ],
        [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          s("A9", "booked", 374),
        ],
        [
          s("F3", "female", 495),
          s("F4", "female", 495),
          s("F5", "female", 495),
          s("F6", "female", 495),
          null,
          s("M1", "male", 540),
          s("M2", "male", 540),
          s("M3", "booked", 540),
          s("M4", "male", 540),
        ],
        [
          s("A10", "available", 374),
          s("A11", "booked", 374),
          s("A12", "available", 374),
          s("A13", "available", 374),
          null,
          s("M5", "male", 540),
          s("M6", "booked", 540),
          s("M7", "male", 540),
          s("M8", "male", 540),
        ],
      ],
    },
    {
      id: 3,
      operatorName: "Neeta tours & travels",
      busType: "Bharat Benz A/C Seater (2+2)",
      departureTime: "08:40",
      departureDate: "02 Jan",
      from: "Mumbai",
      arrivalTime: "13:50",
      arrivalDate: "02 Jan",
      to: "Pune",
      duration: "6h 10m",
      price: 1650,
      seatsAvailable: 8,
      priceTiers: [374, 450, 495, 540],
      footerTags: [
        "Boarding & Dropping points",
        "Cancellations Policy",
        "Amenities",
      ],
      boardingPoints: [
        {
          name: "Andheri (E) - Shivaji Travels",
          subLabel: "Andheri East",
          time: "22:50",
        },
        { name: "Dadar - Kailash Travels", subLabel: "Dadar", time: "25:00" },
        { name: "Thane Station", subLabel: "Thane", time: "20:30" },
      ],
      seatLayout: [
        [
          s("A1", "available", 374),
          null,
          s("A2", "booked", 374),
          s("A3", "booked", 374),
          null,
          s("B1", "available", 450),
          s("B2", "booked", 450),
          s("B3", "available", 450),
          s("B4", "booked", 450),
        ],
        [
          s("A4", "available", 374),
          null,
          s("A5", "booked", 374),
          s("A6", "available", 374),
          null,
          s("B5", "booked", 450),
          s("B6", "booked", 450),
          s("F1", "female", 495),
          s("F2", "female", 495),
        ],
        [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          s("A9", "available", 374),
        ],
        [
          s("F3", "female", 495),
          s("F4", "female", 495),
          s("F5", "booked", 495),
          s("F6", "female", 495),
          null,
          s("M1", "booked", 540),
          s("M2", "male", 540),
          s("M3", "male", 540),
          s("M4", "booked", 540),
        ],
        [
          s("A10", "booked", 374),
          s("A11", "available", 374),
          s("A12", "booked", 374),
          s("A13", "available", 374),
          null,
          s("M5", "male", 540),
          s("M6", "booked", 540),
          s("M7", "booked", 540),
          s("M8", "male", 540),
        ],
      ],
    },
  ];

  return (
    <>
      <BusSearch />
      {/* <BusSeatSelection buses={sampleBuses} from="Mumbai" to="Pune" />
      <PassengerDetailsForm /> */}
      <PopularRoutes />
    </>
  );
};

export default Index;
